### ISSUE TITLE
Lesson6

### ISSUE THREAD

**Issue by aishize** [MariaDikhtiievska/TeyMax#1]
В целом все хорошо

Доп.задание (+ баллы)

Сделать через Map
![image](https://user-images.githubusercontent.com/58956219/143766976-9233a037-a21c-4219-a971-bd4ba063b4d8.png)

объявления функций function functionName () {}, переписать с const functionName = () => {}

У тебя создается некоторый враппер, который ты маунтишь в body, вынеси эту логику в отдельную функцию createWrapper, которая будет возвращать этот элемент, позже используй его, чтобы замаунить дочерние элементы
![image](https://user-images.githubusercontent.com/58956219/143767079-13688393-85f2-4d00-83de-5da5ebfa1514.png)

у тебя есть функция clicked, название не передает назначение функции, перепиши на subscribeClickEvent
Также, необходимо переписать блок else в этой функции
![image](https://user-images.githubusercontent.com/58956219/143767665-2f67abdc-e6f1-4087-8a15-f3ea935accfa.png)

**Comment by MariaDikhtiievska** [comment]
Залила, постаралась сделать, как сказал
